### ISSUE TITLE
Argon produce un error al ejecutar webtrees 2.1.15

### ISSUE THREAD

**Issue by BernatBanyuls** [jchue/argon-webtrees-theme#22]
No puedo ejecutar webtrees con el módulo "Argon" instalado. Produce el siguiente error.
¿Alguna sugerencia?
Gracias.

ErrorException: filemtime(): stat failed for /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/modules_v4/argon/resources/js/script.js in /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/app/Module/ModuleCustomTrait.php:155 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}() #1 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/app/Module/ModuleCustomTrait.php(155): filemtime() #2 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/modules_v4/argon/module.php(160): Fisharebest\Webtrees\Module\MinimalTheme@anonymous->assetUrl() #3 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/resources/views/layouts/default.phtml(185): Fisharebest\Webtrees\Module\MinimalTheme@anonymous->bodyContent() #4 [internal function]: Fisharebest\Webtrees\View::{closure}() #5 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/vendor/illuminate/collections/Collection.php(695): array_map() #6 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/resources/views/layouts/default.phtml(186):

**Comment by jchue** [comment]
Hi, @BernatBanyuls. Are you using the source code or the compiled argon .zip file? Using the source code requires you to install composer and npm dependencies (see the README).

---

Hola, @BernatBanyuls. ¿Está utilizando el código fuente o el archivo .zip de argón compilado? El uso del código fuente requiere que instale las dependencias de composer y npm (consulte el README).

**Comment by yanndc** [comment]
I got the same error using thr zip file download. Its like files were missing. Like this js folder.

**Comment by jchue** [comment]
Closing due to inactivity; feel free to open a new issue if you find any other problems.

---

Cierre por inactividad; siéntete libre de abrir un nuevo número si encuentras algún otro problema.
